-- Add AI-generated goal description and difficulty rationale to tasks
-- These are generated by the roadmap-generator edge function per-task
-- using the user's questionnaire data and the task's attributes

ALTER TABLE public.tasks
ADD COLUMN IF NOT EXISTS goal_description text;

COMMENT ON COLUMN public.tasks.goal_description IS 'AI-generated explanation of why this specific task matters for this user, using their roadmap data';

ALTER TABLE public.tasks
ADD COLUMN IF NOT EXISTS difficulty_rationale text;

COMMENT ON COLUMN public.tasks.difficulty_rationale IS 'AI-generated breakdown of why this task has its specific difficulty score, referencing the task attributes';
